### ISSUE TITLE
Padding around column seperator

### ISSUE THREAD

**Issue by q-wertz** [hvalev/markdownTable#2]
Currently there is no whitespace around the column separator which is as far as I know totally conforming to the standard but (in my personal opinion) a little bit hard to read in the raw view (and I have never seen it that way).

e.g.
```python
test = [{"A": "row1_A", "B": "row1_B", "C": "row1_C"},
        {"A": "row2_A", "B": "row2_B", "C": "row2_C"},
        {"A": "row3_A", "B": "row3_B", "C": "row3_C"}]

tabletest = mdT.markdownTable(test).setParams(row_sep="markdown", 
                                              padding_weight="right", 
                                              quote=False).getMarkdown()
print(tabletest)
```
Output:
```
|A     |B     |C     |
|------|------|------|
|row1_A|row1_B|row1_C|
|row2_A|row2_B|row2_C|
|row3_A|row3_B|row3_C|
```

I would prefer: 
```
| A      | B      | C      |
| ------ | ------ | ------ |
| row1_A | row1_B | row1_C |
| row2_A | row2_B | row2_C |
| row3_A | row3_B | row3_C |
```

Do you accept a PR for this (maybe also as an optional setting) or do you want it to keep it the way it is?

**Comment by hvalev** [comment]
Hmm, it's an interesting idea, but I would like to clarify two things:
* Would this option be for viewing purposes only or also as a way to output the formatted table?
* Wouldn't padding_width=2 and padding_weight=centerleft or centerright achieve that already? Since, if you add two padding characters to a table with items of uniform length they will be distributed equally on both sides with that combination of parameters.

**Comment by q-wertz** [comment]
> - Would this option be for viewing purposes only or also as a way to output the formatted table?

I think it would be beneficial for both cases. The outputted table is for example used in my case to semi-autogenerate a markdown file that is usually only viewed rendered. But when editing the raw Markdown file it would also enhance the readability of the raw Markdown file

> - Wouldn't padding_width=2 and padding_weight=centerleft or centerright achieve that already? Since, if you add two padding characters to a table with items of uniform length they will be distributed equally on both sides with that combination of parameters.

In this special case the result would be the same, you are right. But this is just the case for columns when the content has always the same width. Furthermore it will never work for `padding_weight="left"` or `padding_weight="right"` I think.

**Comment by hvalev** [comment]
Regarding your reply to my first point, I think that this is beyond the scope of the library as it is meant to simply transform data to a markdown formatting for viewing only. I can, however recommend you to use a monospaced font if you want to edit the raw markdown. In that way, characters in the table will be rendered with the same width.

Regarding the second point, I think that the functionality you are describing is already there. It is also not true that the parameters I mentioned only work for your desired output when the items are of uniform length. For each column the element with the longest length is taken as a template and padding is added to shorter ones. The 'padding_width' simply adds more delimiter characters, where padding_weight chooses how to allocate those. The combination of parameters I gave you should work for all such cases. In my view, the functionality you describe is already there without any modifications needed.

**Comment by q-wertz** [comment]
```python
test = [{"A": "row1_A and additional stuff", "B": "row1_B", "C": "row1_C"},
        {"A": "row2_A", "B": "row2_B and additional stuff", "C": "row2_C"},
        {"A": "row3_A", "B": "row3_B", "C": "row3_C"}]

tabletest = mdT.markdownTable(test).setParams(row_sep="markdown", 
                                              padding_width=2,
                                              padding_weight="centerleft", 
                                              quote=False).getMarkdown()
print(tabletest)
```

Result:
```
|              A              |              B              |    C   |
|-----------------------------|-----------------------------|--------|
| row1_A and additional stuff |            row1_B           | row1_C |
|            row2_A           | row2_B and additional stuff | row2_C |
|            row3_A           |            row3_B           | row3_C |
```

What I would request:
```
| A                           | B                           | C      |
| --------------------------- | --------------------------- | ------ |
| row1_A and additional stuff | row1_B                      | row1_C |
| row2_A                      | row2_B and additional stuff | row2_C |
| row3_A                      | row3_B                      | row3_C |
```<

But nevermind. Not really important.

**Comment by hvalev** [comment]
Ah, I see. You're right and this type of printed output is not possible. I'll think about it. Alternatively, I've been thinking about adding multi-line support for this library, where the idea is basically to split extremely long inputs based on some delimiter character (e.g. in this instance a blank space ' ') and spread them over multiple rows. I believe that this could also address the issue that you're facing. What do you think about that? That is something that I would definitely accept a PR for.

**Comment by q-wertz** [comment]
A multi-line support would be super nice :tada: 

So just let me know how you decided on this issue here (and whether you want it optionally or as the default behavior) as I think the two are different features/issues :)

**Comment by hvalev** [comment]
The functionality for multi-line is very attractive as it can compress otherwise very wide columns. It also addresses the issue that you're having in combination with the padding_width and padding_weight parameters. Alternatively, I could easily implement a separator from the perspective of the column, but that only solves a very niche use-case and is not that useful. From this perspective, I think multi-line is the way to go. I would not have it enabled by default and will include it as an optional named parameter, so that existing implementation relying on a consistent function signature and output don't break. Also, multi-line should not be the default behavior anyway. Would you be interested in submitting a PR for this?

**Comment by q-wertz** [comment]
Just for clarification: 

do you mean multiline in the raw markdown view (which then breaks the rendered table) or in the rendered version (to overwrite the automatic linebreaks)?

**Comment by hvalev** [comment]
Hey, @q-wertz, I finally got around to implement the multiline feature! I am yet to update the documentation, but you can test it out by using the keyword argument `multiline` in `.setParams(...)` where you pass a dict with keys equal to those of the data you're passing and values -- the desired character width of each column. All other formatting options should apply to multiline as well (except the row separator as it shouldn't appear in an entry split over multiple rows). 

A limitation currently is not being able to choose whether entries split over multiple rows fill those top to bottom (current) or bottom to top (not an option yet).
