### ISSUE TITLE
Option for title case headers or custom headers

### ISSUE THREAD

**Issue by ens-scmeeu** [hvalev/markdownTable#3]
It would be nice have the table headers be capitalized via an option without needing to change all the dict keys to capitals. Additionally, it might be nice to allow custom headers different than the dict keys. One use case for this would be a boolean column where you may want to trail the column name with a question mark, for example. Another use case would be if you want spaces in the header.

**Comment by hvalev** [comment]
Although I agree with what you're saying, I believe that this is out of scope for what this library aims to be and namely - to provide a simple and quick way to render data in markdown. The use-cases you are describing can be solved easily in a pre-processing step. Adding those features here would only bloat the code and input parameters.
